# ##########################################################################################################################################
# >> Spawn unique markers meshes
#
# :: Can be used as anchor mesh (same one can be spawned multiple times)
#    > They can be spawned and adjusted in-game via the imgui menu
#
# ~~ Parameters
#   {          
#       #                                   comment         
#       marker_num =                        num of marker                                                           [Int 0-Inf]
#       position = []                       position of the marker mesh                                             [3D Vector]
#       rotation = []                       rotation of the marker mesh                                             [3D Vector]
#       scale = []                          scale of the marker mesh                                                [3D Vector]
#       cull_distance =                     disable drawing of marker mesh after this distance from the player      [Float]
#       spawn_on = {
#           weather = "TYPE"                only spawn marker when THIS weather is active                           [STRING] - [EXTRASUNNY, SUNNY, SUNNY_WINDY, CLOUDY, RAIN, DRIZZLE, FOGGY, LIGHTNING]
#           weather_transition_value =      transition value the weather needs to be at for the marker to show      [Float 0-1] 
#           between_hours = [from, to]      only spawn marker between certain hours (from-to)                       [2D Int]
#       }
#   }, 
#   { ... },

MARKER = [

    # first safehouse test
    { marker_num = 170, position = [895.40, -495.05, 18.91], rotation = [0.00, 0.00, 0.00], scale = [1.00, 1.00, 1.00], cull_distance = 15.00 },

    # seabed plane
    { marker_num = 1000, position = [552.59, 530.76, 16.72], rotation = [0.00, 0.00, 0.00], scale = [50.00, 50.00, 1.00] },

    # tlad safehouse
    { marker_num = 570, position = [-1721.77, 347.40, 26.00], rotation = [0.00, 0.00, 0.00], scale = [1.00, 1.00, 1.00], cull_distance = 50.00 },
]



# ##########################################################################################################################################
# >> Ignore Game Lights
# 
# :: Can be used to disable the translation of specified game lights to remix lights 
# :: Requires light hash to be stable (not moving)
# 
# :: How to retrieve hashes:
#    > Visualize hashes in 3D Space (GUI -> Map Settings -> Ignore Game Lights -> Draw Hash Visualization)
#    > DoubleClick hashes in list to ignore lights and export to clipboard when done -> override IGNORE_LIGHTS with clipboard data
#
# ~~ IGNORE_LIGHTS = [
#     0x0, 0x1, 0x2, ...            [uint array - hex format]
# ]                                                                                              

IGNORE_LIGHTS = [
    0x32734E7F
]



# ##########################################################################################################################################
# >> Allow Game Lights
# 
# :: This can be used to whitelist disabled filler lights
# :: Only useful if 'ignore filler lights' is enabled
# 
# :: How to retrieve hashes:
#    > Visualize hashes in 3D Space (GUI -> Map Settings -> Ignore Game Lights -> Draw Hash Visualization)
#    > DoubleClick hashes in list to ignore lights and export to clipboard when done -> override ALLOW_LIGHTS with clipboard data
#
# ~~ ALLOW_LIGHTS = [
#     0x0, 0x1, 0x2, ...            [uint array - hex format]
# ]      

ALLOW_LIGHTS = [
    0x8C8CB2FC
]



# ##########################################################################################################################################
# >> Light Overrides
# 
# :: This can be used to override light settings.
# :: Requires a stable light hash!
# 
# :: How to retrieve hashes & create overrides:
#    > Visualize hashes in 3D Space (GUI -> Map Settings -> Ignore Game Lights -> Draw Hash Visualization)
#    > Select hash in list and tweak settings. Make sure to export to clipboard when done -> override LIGHT_OVERRIDES with clipboard data
#
# ~~ LIGHT_OVERRIDES = [
#   {          
#       #                   comment         
#       hash =              hash of light                                   [uint - hex format]
#       pos = []            position of light                        [opt.] [3D Vector]
#       dir = []            direction of light                       [opt.] [3D Vector]
#       color = []          color of light                           [opt.] [3D Vector]
#       radius =            radius of light                          [opt.] [Float]
#       intensity =         intensity of light                       [opt.] [Float]
#       outer_cone_angle =  outer cone angle of light                [opt.] [Float]
#       inner_cone_angle =  inner cone angle of light                [opt.] [Float]
#       volumetric_scale =  volumetric scale of light                [opt.] [Float]
#       light_type =        0: sphere -- 1: spotlight                [opt.] [Bool]
#   }, 
#   { ... },
# ]      

LIGHT_OVERRIDES = [
]



# ##########################################################################################################################################
# >> Anti Culling Tweaks
# 
# :: The anti-cull logic might miss certain meshes (eg. if a skyscraper is made up of multiple smaller meshes) 
# :: so this can be used tweak anti-culling behavior for specified meshes. 
# :: Meshes will only be forced up until the specified distance of the 'category' they are in.
# 
# :: How to retrieve hashes:
#    > Visualize model info in 3D Space (GUI -> Map Settings -> Anti Culling Tweaks -> Draw Visualization)
#    > Select index of model and a add it to an existing categor
#    > ! Export to clipboard when done -> override ANTICULL with clipboard data
#
# ~~ ANTICULL = [
#   {          
#       #                   comment         
#       distance =          distance (from player) until forcing logic is active (0 = always forced)    [int 0-inf]
#       indices = []        indices of meshes                                                           [int array]
#   }, 
#   { ... },
# ]      
ANTICULL = [

    # skyscrapers
    { distance = 500, indices = [
        24570, 25679, 26510, 27234, 15048, 27224, 24569, 21376, 19493, 
        21652, 21400, 21377, 21391, 21218, 19492, 19491, 15424, 15426, 15418, 
        15417, 15365, 15363
    ]},
]
