# ##########################################################################################################################################
# >> Spawn unique markers meshes
#
# :: Can be used as anchor mesh (same one can be spawned multiple times)
#    > They can be spawned and adjusted in-game via the imgui menu
#
# ~~ Parameters
#   {          
#       #                   comment         
#       marker_num =        num of marker                                                           [int 0-inf]
#       position = []       position of the marker mesh                                             [3D Vector]
#       rotation = []       rotation of the marker mesh                                             [3D Vector]
#       scale = []          scale of the marker mesh                                                [3D Vector]
#       cull_distance =     disable drawing of marker mesh after this distance from the player      [Float]
#   }, 
#   { ... },

MARKER = [

    # first safehouse test
    { marker_num = 170, position = [895.40, -495.05, 18.91], rotation = [0.00, 0.00, 0.00], scale = [1.00, 1.00, 1.00], cull_distance = 15.00 },

    # seabed plane
    { marker_num = 1000, position = [552.59, 530.76, 16.72], rotation = [0.00, 0.00, 0.00], scale = [50.00, 50.00, 1.00] },

    # tlad safehouse
    { marker_num = 570, position = [-1721.77, 347.40, 26.00], rotation = [0.00, 0.00, 0.00], scale = [1.00, 1.00, 1.00], cull_distance = 50.00 },
]

# ##########################################################################################################################################
# >> Ignore Game Lights
# 
# :: Can be used to disable the translation of specified game lights to remix lights 
# :: Requires light hash to be stable (not moving)
# 
# :: How to retrieve hashes:
#    > Visualize hashes in 3D Space (GUI -> Map Settings -> Ignore Game Lights -> Draw Hash Visualization)
#    > DoubleClick hashes in list to ignore lights and export to clipboard when done -> override IGNORE_LIGHTS with clipboard data
#
# ~~ IGNORE_LIGHTS = [
#     0x0, 0x1, 0x2, ...            [uint array - hex format]
# ]                                                                                              

IGNORE_LIGHTS = [
    0x32734E7F
]

# ##########################################################################################################################################
# >> Allow Game Lights
# 
# :: This can be used to whitelist disabled filler lights
# :: Only useful if 'ignore filler lights' is enabled
# 
# :: How to retrieve hashes:
#    > Visualize hashes in 3D Space (GUI -> Map Settings -> Ignore Game Lights -> Draw Hash Visualization)
#    > DoubleClick hashes in list to ignore lights and export to clipboard when done -> override ALLOW_LIGHTS with clipboard data
#
# ~~ ALLOW_LIGHTS = [
#     0x0, 0x1, 0x2, ...            [uint array - hex format]
# ]      

ALLOW_LIGHTS = [
    0x8C8CB2FC
]
