# ##########################################################################################################################################
# >> Spawn unique markers meshes
#
# :: Can be used as anchor mesh (same one can be spawned multiple times)
#    > They can be spawned and adjusted in-game via the imgui menu
#
# ~~ Parameters
#   {          
#       #                                   comment         
#       marker_num =                        num of marker                                                           [Int 0-Inf]
#       position = []                       position of the marker mesh                                             [3D Vector]
#       rotation = []                       rotation of the marker mesh                                             [3D Vector]
#       scale = []                          scale of the marker mesh                                                [3D Vector]
#       cull_distance =                     disable drawing of marker mesh after this distance from the player      [Float]
#       spawn_on = {
#           weather = "TYPE"                only spawn marker when THIS weather is active                           [STRING] - [EXTRASUNNY, SUNNY, SUNNY_WINDY, CLOUDY, RAIN, DRIZZLE, FOGGY, LIGHTNING]
#           weather_transition_value =      transition value the weather needs to be at for the marker to show      [Float 0-1] 
#           between_hours = [from, to]      only spawn marker between certain hours (from-to)                       [2D Int]
#       }
#   }, 
#   { ... },

MARKER = [

    # first safehouse test
    { marker_num = 170, position = [895.40, -495.05, 18.91], rotation = [0.00, 0.00, 0.00], scale = [1.00, 1.00, 1.00], cull_distance = 15.00 },

    # seabed plane
    { marker_num = 1000, position = [552.59, 530.76, 16.72], rotation = [0.00, 0.00, 0.00], scale = [50.00, 50.00, 1.00] },

    # tlad safehouse
    { marker_num = 570, position = [-1721.77, 347.40, 26.00], rotation = [0.00, 0.00, 0.00], scale = [1.00, 1.00, 1.00], cull_distance = 50.00 },

    # downtown skyscrapers shadowcasters 01
    { marker_num = 300, position = [-57.10, 594.42, 74.78], rotation = [0.00, 0.00, 0.00], scale = [1.00, 1.00, 1.00], cull_distance = 600.00 },

    # downtown skyscrapers shadowcasters 02
    { marker_num = 301, position = [-215.06, 381.53, 87.49], rotation = [0.00, 0.00, 0.00], scale = [1.00, 1.00, 1.00], cull_distance = 600.00 },

    # downtown skyscrapers shadowcasters 03
    { marker_num = 302, position = [-281.44, -0.08, 104.94], rotation = [0.00, 0.00, 0.00], scale = [1.00, 1.00, 1.00], cull_distance = 600.00 },

    # downtown skyscrapers shadowcasters 04
    { marker_num = 303, position = [-50.80, -561.45, 64.70], rotation = [0.00, 0.00, 0.00], scale = [1.00, 1.00, 1.00], cull_distance = 800.00 },
]



# ##########################################################################################################################################
# >> Ignore Game Lights
# 
# :: Can be used to disable the translation of specified game lights to remix lights 
# :: Requires light hash to be stable (not moving)
# 
# :: How to retrieve hashes:
#    > Visualize hashes in 3D Space (GUI -> Map Settings -> Ignore Game Lights -> Draw Hash Visualization)
#    > DoubleClick hashes in list to ignore lights and export to clipboard when done -> override IGNORE_LIGHTS with clipboard data
#
# ~~ IGNORE_LIGHTS = [
#     0x0, 0x1, 0x2, ...            [uint array - hex format]
# ]                                                                                              

IGNORE_LIGHTS = [
    0x32734E7F, 0x79B4AF95, 0xDA6E0F5A, 0x403E165F, 0x8207760C, 0x74D3E6F, 0x2BF21803, 0xB9B7A3F3, 0x352AEAAC, 
    0xDF6EE45C, 0x2CCE00DE, 0x32AE2E4D, 0x9EC26F3E, 0x445F053B, 0x9ECD1EF7, 0x84CD9FFE, 0xDE7EFC36, 0xFF9457D5, 0x25EE6A9E, 
    0x4C61B845
]



# ##########################################################################################################################################
# >> Allow Game Lights
# 
# :: This can be used to whitelist disabled filler lights
# :: Only useful if 'ignore filler lights' is enabled
# 
# :: How to retrieve hashes:
#    > Visualize hashes in 3D Space (GUI -> Map Settings -> Ignore Game Lights -> Draw Hash Visualization)
#    > DoubleClick hashes in list to ignore lights and export to clipboard when done -> override ALLOW_LIGHTS with clipboard data
#
# ~~ ALLOW_LIGHTS = [
#     0x0, 0x1, 0x2, ...            [uint array - hex format]
# ]      

ALLOW_LIGHTS = [
    0x8C8CB2FC
]



# ##########################################################################################################################################
# >> Light Overrides
# 
# :: This can be used to override light settings.
# :: Requires a stable light hash!
# 
# :: How to retrieve hashes & create overrides:
#    > Visualize hashes in 3D Space (GUI -> Map Settings -> Ignore Game Lights -> Draw Hash Visualization)
#    > Select hash in list and tweak settings. Make sure to export to clipboard when done -> override LIGHT_OVERRIDES with clipboard data
#
# ~~ LIGHT_OVERRIDES = [
#   {          
#       #                   comment         
#       hash =              hash of light                                   [uint - hex format]
#       pos = []            position of light                        [opt.] [3D Vector]
#       dir = []            direction of light                       [opt.] [3D Vector]
#       color = []          color of light                           [opt.] [3D Vector]
#       radius =            radius of light                          [opt.] [Float]
#       intensity =         intensity of light                       [opt.] [Float]
#       outer_cone_angle =  outer cone angle of light                [opt.] [Float]
#       inner_cone_angle =  inner cone angle of light                [opt.] [Float]
#       volumetric_scale =  volumetric scale of light                [opt.] [Float]
#       light_type =        0: sphere -- 1: spotlight                [opt.] [Bool]
#   }, 
#   { ... },
# ]      

LIGHT_OVERRIDES = [
    { hash = 0x36B52713, pos = [892.45, -504.40, 17.94], radius = 6.17, intensity = 8.68 },
    { hash = 0xA4D59F91, pos = [895.80, -493.90, 20.68], radius = 6.80, intensity = 2.39 },
    { hash = 0xC5A12985, pos = [888.69, -503.36, 22.17], radius = 5.95, intensity = 9.55 },
    { hash = 0x28B1B6E6, pos = [895.82, -493.93, 20.62], color = [0.88, 0.82, 0.44], radius = 3.40, intensity = 46.10 },
    { hash = 0xBCB9080D, pos = [885.61, -499.77, 20.68], radius = 13.38, intensity = 2.00 },
    { hash = 0x124330B1, pos = [895.77, -496.50, 20.67], color = [0.97, 0.90, 0.58], radius = 5.30, intensity = 4.00 },
]



# ##########################################################################################################################################
# >> Anti Culling Tweaks
# 
# :: The anti-cull logic might miss certain meshes (eg. if a skyscraper is made up of multiple smaller meshes) 
# :: so this can be used tweak anti-culling behavior for specified meshes. 
# :: Meshes will only be forced up until the specified distance of the 'category' they are in.
# 
# :: How to retrieve hashes:
#    > Visualize model info in 3D Space (GUI -> Map Settings -> Anti Culling Tweaks -> Draw Visualization)
#    > Select index of model and a add it to an existing categor
#    > ! Export to clipboard when done -> override ANTICULL with clipboard data
#
# ~~ ANTICULL = [
#   {          
#       #                   comment         
#       distance =          distance (from player) until forcing logic is active (0 = always forced)    [int 0-inf]
#       indices = []        indices of meshes                                                           [int array]
#   }, 
#   { ... },
# ]      
ANTICULL = [

    # skyscrapers
    { distance = 500, indices = [
        24570, 25679, 26510, 27234, 15048, 27224, 24569, 21376, 19493, 
        21652, 21400, 21377, 21391, 21218, 19492, 19491, 15424, 15426, 15418, 
        15417, 15365, 15363
    ]},
]
